// Vite plugin: re-runs scripts/buildMidiSpecs.mjs when DOCS/midi/*.md changes.
// Adds the MD files to the dev-server watch list and runs the generator
// in-process on change so the autogenerated TS files refresh without restarting.

import { spawn } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { existsSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const generatorPath = resolve(repoRoot, 'scripts/buildMidiSpecs.mjs');
const specsDir = resolve(repoRoot, 'DOCS/midi');

let running = false;
let queued = false;

function runGenerator(label) {
  if (running) {
    queued = true;
    return;
  }
  running = true;
  const started = Date.now();
  const child = spawn(process.execPath, [generatorPath], {
    cwd: repoRoot,
    stdio: 'inherit',
  });
  child.on('exit', (code) => {
    running = false;
    const ms = Date.now() - started;
    if (code === 0) {
      console.log(`[vite-midi-specs] regenerated (${label}, ${ms}ms)`);
    } else {
      console.error(`[vite-midi-specs] generator exited with code ${code}`);
    }
    if (queued) {
      queued = false;
      runGenerator('coalesced');
    }
  });
}

export default function midiSpecsPlugin() {
  return {
    name: 'artbastard-midi-specs',
    enforce: 'pre',
    buildStart() {
      if (!existsSync(generatorPath)) {
        this.warn(`buildMidiSpecs.mjs not found at ${generatorPath} — skipping MIDI spec generation`);
        return;
      }
      runGenerator('buildStart');
    },
    configureServer(server) {
      if (!existsSync(specsDir)) return;
      server.watcher.add(`${specsDir}/**/*.md`);
      server.watcher.on('change', (file) => {
        if (file.includes(`${specsDir.replace(/\\/g, '/')}`) || file.includes('DOCS/midi/')) {
          runGenerator(`change:${file.split(/[\\/]/).pop()}`);
        }
      });
      server.watcher.on('add', (file) => {
        if (file.includes('DOCS/midi/')) runGenerator(`add:${file.split(/[\\/]/).pop()}`);
      });
    },
  };
}
