// MIDI spec codegen: DOCS/midi/*.md → react-app/src/midi/generated/*.ts
//
// Domain module under scripts/specs/. Use via scripts/buildSpecs.mjs (umbrella)
// or directly via scripts/buildMidiSpecs.mjs (back-compat shim).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  readSpecFile,
  parseNumLike,
  parseChannels,
  parseAliases,
  makeAssert,
  jsonPretty as json,
} from './shared/mdParser.mjs';

const assert = makeAssert('buildMidiSpecs');

// Preserve the legacy header verbatim so generated TS files are byte-identical
// to the previous one-script build chain.
const GENERATED_HEADER = `// AUTOGENERATED by scripts/buildMidiSpecs.mjs — DO NOT EDIT.
// Edit the source spec in DOCS/midi/*.md and run \`npm run build-midi-specs\`.
`;

function readSpec(specDir, name) {
  return readSpecFile(join(specDir, `${name}.md`));
}

// ─── Per-spec readers + validators ──────────────────────────────────────────

function buildApc40Spec(specDir) {
  const { file, frontmatter: fm, tables } = readSpec(specDir, 'apc40');
  assert(fm.spec === 'apc40', file, 'frontmatter spec must be "apc40"');
  assert(Array.isArray(fm.models) && fm.models.length, file, 'frontmatter.models[] required');
  assert(fm.grid && fm.grid.rows && fm.grid.cols, file, 'frontmatter.grid {rows, cols} required');

  const noteBindings = (tables['note-bindings'] || []).map((r, i) => {
    const note = parseNumLike(r.note);
    assert(note !== undefined, file, `note-bindings row ${i + 1}: bad note "${r.note}"`);
    return {
      controlKey: r.controlKey,
      channels: parseChannels(r.channels),
      note,
      action: r.action,
      velocityCheck: r.velocityCheck || null,
    };
  });
  assert(noteBindings.length > 0, file, 'note-bindings table is empty');

  const ccBindings = (tables['cc-bindings'] || []).map((r, i) => {
    const cc = parseNumLike(r.cc);
    assert(cc !== undefined, file, `cc-bindings row ${i + 1}: bad cc "${r.cc}"`);
    return {
      controlKey: r.controlKey,
      channels: parseChannels(r.channels),
      cc,
      action: r.action,
      direction: r.direction || 'in',
    };
  });
  assert(ccBindings.length > 0, file, 'cc-bindings table is empty');

  const deviceKnobs = (tables['device-knob-role-assignments-default'] || []).map((r, i) => {
    const slot = parseNumLike(r.slot);
    const cc = parseNumLike(r.cc);
    assert(slot !== undefined && cc !== undefined, file, `device-knob row ${i + 1}: bad slot/cc`);
    return { slot, cc, controlName: r.controlName, roleLabel: r.roleLabel };
  });

  const catalog = (tables['operator-facing-control-catalog'] || []).map((r, i) => {
    assert(r.key && r.category && r.label, file, `catalog row ${i + 1}: missing key/category/label`);
    return { key: r.key, category: r.category, label: r.label, description: r.description || '' };
  });

  return {
    models: fm.models,
    init: fm.init || { sendDeviceInquiry: false, modeInitSysExHex: '' },
    grid: { rows: fm.grid.rows, cols: fm.grid.cols, slotsPerDeck: fm.grid.slotsPerDeck || (fm.grid.rows * fm.grid.cols) },
    sceneNaming: fm.sceneNaming || { pattern: 'APC40 Deck {deck} {slot:02}', decks: ['A', 'B'] },
    transport: fm.transport || {},
    master: fm.master || {},
    noteBindings,
    ccBindings,
    deviceKnobs,
    catalog,
  };
}

function buildLedFeedbackSpec(specDir) {
  const { file, frontmatter: fm, tables } = readSpec(specDir, 'led-feedback');
  assert(fm.spec === 'led-feedback', file, 'frontmatter spec must be "led-feedback"');
  const velocities = (tables['velocities'] || []).map((r, i) => {
    const value = parseNumLike(r.value);
    assert(r.name && value !== undefined, file, `velocities row ${i + 1}: missing name/value`);
    return { name: r.name, value, meaning: r.meaning || '' };
  });
  assert(velocities.length > 0, file, 'velocities table is empty');

  const behavior = (tables['behavior'] || []).map((r, i) => {
    assert(r.controlKey && r.states, file, `behavior row ${i + 1}: missing controlKey/states`);
    const rules = r.states.split(';').map((part) => {
      const [cond, vel] = part.split('=').map((p) => p.trim());
      assert(cond && vel, file, `behavior row ${i + 1}: bad rule "${part}"`);
      return { condition: cond, velocity: vel };
    });
    return { controlKey: r.controlKey, rules };
  });

  return {
    ringLeds: fm.ringLeds || { enabled: false, coalesceMs: 50, deviceRingBaseCc: 0x18, trackRingBaseCc: 0x38, midiChannel: 0 },
    errorHandling: fm.errorHandling || { maxErrorsPerSecond: 5, toastDebounceMs: 5000 },
    velocities,
    behavior,
  };
}

function buildDeviceDetectionSpec(specDir) {
  const { file, frontmatter: fm, tables } = readSpec(specDir, 'device-detection');
  assert(fm.spec === 'device-detection', file, 'frontmatter spec must be "device-detection"');
  const patterns = (tables['patterns'] || []).map((r, i) => {
    assert(r.kind && r.pattern, file, `patterns row ${i + 1}: missing kind/pattern`);
    return { kind: r.kind, pattern: r.pattern };
  });
  const templateHints = (tables['template-hints'] || []).map((r, i) => {
    assert(r.pattern && r.templateId, file, `template-hints row ${i + 1}: missing fields`);
    return { pattern: r.pattern, templateId: r.templateId };
  });
  return { patterns, templateHints };
}

function buildSuperControlRolesSpec(specDir) {
  const { file, frontmatter: fm, tables } = readSpec(specDir, 'super-control-roles');
  assert(fm.spec === 'super-control-roles', file, 'frontmatter spec must be "super-control-roles"');
  const priority = (tables['device-role-priority-auto-bank-order'] || []).map((r, i) => {
    assert(r.label && r.controlName, file, `device-role-priority row ${i + 1}: missing label/controlName`);
    return { label: r.label, controlName: r.controlName, aliases: parseAliases(r.aliases) };
  });
  const trackControl = (tables['track-control-knob-assignment-fixed'] || []).map((r, i) => {
    const slot = parseNumLike(r.slot);
    assert(slot !== undefined && r.controlName, file, `track-control row ${i + 1}: bad slot/controlName`);
    return { slot, label: r.label, controlName: r.controlName, aliases: parseAliases(r.aliases) };
  });
  return {
    fullOnExcludedTypes: fm.fullOnExcludedTypes || [],
    devicePriority: priority,
    trackControl,
  };
}

function buildRoliColorPickerSpec(specDir) {
  const { file, frontmatter: fm } = readSpec(specDir, 'roli-color-picker');
  assert(fm.spec === 'roli-color-picker', file, 'frontmatter spec must be "roli-color-picker"');
  assert(fm.grid && fm.grid.cols && fm.grid.rows, file, 'frontmatter.grid required');
  assert(fm.modes && fm.modes.wheel && fm.modes.palette, file, 'frontmatter.modes.{wheel,palette} required');
  const roleTargets = fm.roleTargets || {};
  const targets = ['red', 'green', 'blue'].map((role) => ({
    role,
    aliases: parseAliases((roleTargets[role] && (roleTargets[role].aliases || roleTargets[role])) || role),
  }));
  return {
    grid: fm.grid,
    defaultMode: fm.defaultMode || 'wheel',
    modes: fm.modes,
    roleTargets: targets,
  };
}

// ─── Emitters ───────────────────────────────────────────────────────────────

function emitApc40(spec) {
  return `${GENERATED_HEADER}
export type Apc40ModelId = 'apc40-mk1' | 'apc40-mk2';

export interface Apc40Model { id: Apc40ModelId; detect: string[]; }
export interface Apc40ChannelRange { kind: 'range'; from: number; to: number; }
export interface Apc40ChannelSingle { kind: 'single'; channel: number; }
export type Apc40Channels = Apc40ChannelRange | Apc40ChannelSingle | 'any';

export interface Apc40NoteBinding {
  controlKey: string;
  channels: Apc40Channels;
  note: number;
  action: string;
  velocityCheck: 'gt0' | 'press-release' | null;
}
export interface Apc40CcBinding {
  controlKey: string;
  channels: Apc40Channels;
  cc: number;
  action: string;
  direction: 'in' | 'out';
}
export interface Apc40DeviceKnob { slot: number; cc: number; controlName: string; roleLabel: string; }
export interface Apc40CatalogEntry { key: string; category: string; label: string; description: string; }

export const APC40_MODELS: Apc40Model[] = ${json(spec.models)};
export const APC40_INIT = ${json(spec.init)} as const;
export const APC40_GRID = ${json(spec.grid)} as const;
export const APC40_SCENE_NAMING = ${json(spec.sceneNaming)} as const;
export const APC40_TRANSPORT_NOTES = ${json(spec.transport)} as const;
export const APC40_MASTER_CC = ${json(spec.master)} as const;
export const APC40_NOTE_BINDINGS: Apc40NoteBinding[] = ${json(spec.noteBindings)};
export const APC40_CC_BINDINGS: Apc40CcBinding[] = ${json(spec.ccBindings)};
export const APC40_DEVICE_KNOB_ASSIGNMENTS: Apc40DeviceKnob[] = ${json(spec.deviceKnobs)};
export const APC40_CATALOG: Apc40CatalogEntry[] = ${json(spec.catalog)};

export const APC40_GRID_ROWS = APC40_GRID.rows;
export const APC40_GRID_COLS = APC40_GRID.cols;
export const APC40_GRID_SLOT_COUNT = APC40_GRID.slotsPerDeck;

export function apc40FormatSceneName(deck: 'A' | 'B', slotIndex: number): string {
  const slot = Math.max(0, Math.min(APC40_GRID_SLOT_COUNT - 1, slotIndex));
  return APC40_SCENE_NAMING.pattern
    .replace('{deck}', deck)
    .replace(/{slot:(\\d+)}/g, (_m, w) => String(slot + 1).padStart(parseInt(w, 10), '0'))
    .replace('{slot}', String(slot + 1));
}
`;
}

function emitLedFeedback(spec) {
  const velMap = {};
  for (const v of spec.velocities) velMap[v.name] = v.value;
  return `${GENERATED_HEADER}
export interface LedVelocity { name: string; value: number; meaning: string; }
export interface LedBehaviorRule { condition: string; velocity: string; }
export interface LedBehavior { controlKey: string; rules: LedBehaviorRule[]; }

export const LED_VELOCITIES: LedVelocity[] = ${json(spec.velocities)};
export const LED = ${json(velMap)} as const;
export const LED_BEHAVIOR: LedBehavior[] = ${json(spec.behavior)};
export const LED_RING_CONFIG = ${json(spec.ringLeds)} as const;
export const LED_ERROR_HANDLING = ${json(spec.errorHandling)} as const;

export const BLINK_LED_VALUES = new Set<number>([
  LED.LED_GREEN_BLINK ?? -1,
  LED.LED_RED_BLINK ?? -1,
  LED.LED_ORANGE_BLINK ?? -1,
].filter((v) => v >= 0));
`;
}

function emitDeviceDetection(spec) {
  return `${GENERATED_HEADER}
export type DetectedMidiControllerKind = 'apc40' | 'roli-lightpad';
export type MidiControllerTemplateId = 'x_touch_mackie' | 'apc40_mk1';

export const DEVICE_PATTERNS: ReadonlyArray<{ kind: DetectedMidiControllerKind; pattern: string }> = ${json(spec.patterns)};
export const TEMPLATE_HINTS: ReadonlyArray<{ pattern: string; templateId: MidiControllerTemplateId }> = ${json(spec.templateHints)};

export function detectControllerKind(name: string): DetectedMidiControllerKind | null {
  const lower = (name || '').toLowerCase();
  for (const p of DEVICE_PATTERNS) {
    if (lower.includes(p.pattern)) return p.kind;
  }
  return null;
}

export function detectTemplateId(name: string): MidiControllerTemplateId | null {
  const lower = (name || '').toLowerCase();
  for (const t of TEMPLATE_HINTS) {
    if (lower.includes(t.pattern)) return t.templateId;
  }
  return null;
}
`;
}

function emitSuperControlRoles(spec) {
  return `${GENERATED_HEADER}
export interface RoleSlot { label: string; controlName: string; aliases: string[]; }
export interface TrackControlRole extends RoleSlot { slot: number; }

export const DEVICE_ROLE_PRIORITY: RoleSlot[] = ${json(spec.devicePriority)};
export const TRACK_CONTROL_ROLES: TrackControlRole[] = ${json(spec.trackControl)};
export const FULL_ON_EXCLUDED_TYPES: ReadonlySet<string> = new Set<string>(${json(spec.fullOnExcludedTypes)});
`;
}

function emitRoliColorPicker(spec) {
  return `${GENERATED_HEADER}
export type RoliColorPickerMode = 'wheel' | 'palette';
export interface RoliColorPickerGrid { cols: number; rows: number; }
export interface RoliColorPickerRoleTarget { role: 'red' | 'green' | 'blue'; aliases: string[]; }

export const ROLI_COLOR_PICKER_GRID: RoliColorPickerGrid = ${json(spec.grid)};
export const ROLI_COLOR_PICKER_DEFAULT_MODE: RoliColorPickerMode = ${json(spec.defaultMode)};
export const ROLI_COLOR_PICKER_MODES = ${json(spec.modes)} as const;
export const ROLI_COLOR_PICKER_ROLE_TARGETS: RoliColorPickerRoleTarget[] = ${json(spec.roleTargets)};
`;
}

// ─── Domain entry point ─────────────────────────────────────────────────────

/** Build all MIDI generated TS files. Returns array of written file basenames. */
export function buildMidi({ rootDir }) {
  const SPEC_DIR = join(rootDir, 'DOCS', 'midi');
  const OUT_DIR = join(rootDir, 'react-app', 'src', 'midi', 'generated');

  if (!existsSync(SPEC_DIR)) {
    console.error(`[buildMidiSpecs] missing spec dir: ${SPEC_DIR}`);
    process.exit(1);
  }
  mkdirSync(OUT_DIR, { recursive: true });

  const outputs = [
    { name: 'apc40Spec.ts',             content: emitApc40(buildApc40Spec(SPEC_DIR)) },
    { name: 'ledFeedbackSpec.ts',       content: emitLedFeedback(buildLedFeedbackSpec(SPEC_DIR)) },
    { name: 'deviceDetectionSpec.ts',   content: emitDeviceDetection(buildDeviceDetectionSpec(SPEC_DIR)) },
    { name: 'superControlRolesSpec.ts', content: emitSuperControlRoles(buildSuperControlRolesSpec(SPEC_DIR)) },
    { name: 'roliColorPickerSpec.ts',   content: emitRoliColorPicker(buildRoliColorPickerSpec(SPEC_DIR)) },
  ];

  const indexContent = `${GENERATED_HEADER}
export * from './apc40Spec';
export * from './ledFeedbackSpec';
export * from './deviceDetectionSpec';
export * from './superControlRolesSpec';
export * from './roliColorPickerSpec';
`;
  outputs.push({ name: 'index.ts', content: indexContent });

  let written = 0;
  for (const f of outputs) {
    const path = join(OUT_DIR, f.name);
    const prev = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (prev !== f.content) {
      writeFileSync(path, f.content, 'utf8');
      written++;
    }
  }

  return { files: outputs.map((o) => o.name), written, outDir: OUT_DIR };
}
